/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#00210e",
        "background": "#fcf9f8",
        "on-primary-fixed-variant": "#822801",
        "primary-container": "#bf542c",
        "on-surface": "#1b1c1c",
        "outline-variant": "#dec0b7",
        "on-tertiary-fixed-variant": "#4d4634",
        "on-tertiary-container": "#fffbff",
        "secondary": "#376847",
        "tertiary-container": "#7d7460",
        "on-primary-container": "#fffbff",
        "primary-fixed": "#ffdbcf",
        "surface-container-lowest": "#ffffff",
        "primary": "#9f3c16",
        "tertiary": "#635b48",
        "surface-dim": "#dcd9d9",
        "surface-container": "#f0eded",
        "surface-bright": "#fcf9f8",
        "on-secondary-fixed-variant": "#1e5031",
        "inverse-primary": "#ffb59c",
        "secondary-container": "#b6edc2",
        "surface": "#fcf9f8",
        "error-container": "#ffdad6",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e5e2e1",
        "secondary-fixed": "#b9efc5",
        "tertiary-fixed": "#ede1c9",
        "outline": "#8a726a",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#ffb59c",
        "surface-container-low": "#f6f3f2",
        "on-error": "#ffffff",
        "inverse-surface": "#303030",
        "inverse-on-surface": "#f3f0ef",
        "on-tertiary-fixed": "#211b0c",
        "surface-tint": "#a23e18",
        "on-primary-fixed": "#390c00",
        "on-surface-variant": "#57423b",
        "on-secondary-container": "#3b6d4b",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#9dd3aa",
        "surface-container-high": "#eae7e7",
        "tertiary-fixed-dim": "#d1c5ae",
        "surface-container-highest": "#e5e2e1",
        "on-background": "#1b1c1c"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "sm": "12px",
        "max-width": "1280px",
        "md": "24px",
        "lg": "48px",
        "base": "8px",
        "xl": "80px",
        "margin-desktop": "40px",
        "gutter": "20px",
        "margin-mobile": "16px",
        "xs": "4px"
      },
      fontFamily: {
        "display-lg": ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope", "sans-serif"],
        "headline-md": ["Manrope", "sans-serif"],
        "headline-lg-mobile": ["Manrope", "sans-serif"],
        "label-sm": ["Manrope", "sans-serif"],
        "label-md": ["Manrope", "sans-serif"],
        "body-md": ["Be Vietnam Pro", "sans-serif"],
        "body-lg": ["Be Vietnam Pro", "sans-serif"]
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}